apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    # 被一个pod读写
    - ReadWriteOnce
  resources:
    requests:
      # 需要一个G的容量
      storage: 1Gi