apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pv-claim
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/data/webook"
    type: DirectoryOrCreate